# Generated by Django 2.2.5 on 2019-09-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoConsumidoMesaAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamentoAberto', models.BooleanField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payres.Mesa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payres.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoMesaAuditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagamentoAberto', models.BooleanField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payres.Mesa')),
            ],
        ),
    ]
